### ISSUE TITLE
Cache 501 SI/DO Average

### ISSUE THREAD

**Issue by thomasmiko** [mischkadb/lidarts#105]
For some functionalities (tooltip, sorting in chat) it is necessary that the average of the most played variant (501 SI/DO) is cached.

The idea is the following:

Creation of a new table statistic_cache, with the field 'user_id' and 'avg_501_si_do'. 

After each game that is completed (games.status is set to completed) this value is recalculated (for player 1, if an online game also for player 2).

Later the table can be extended with more fields - if necessary.

**Comment by mischkadb** [comment]
I like that! I'd implement it just like you described. I would limit it to the last x games or legs. Saves resources and players improve over time.

For now I think we can do the calculation simply in the main task. Later we can use a background worker like RQ and celery when #47 is implemented.

**Comment by thomasmiko** [comment]
To Limit it to the last games sounds good. Maybe the last 50 Games?

**Comment by mischkadb** [comment]
Implemented by https://github.com/mischkadb/lidarts/commit/093104ee354a2dc9b21c0214423dde2ba6ee84fc
