### ISSUE TITLE
Re-Design Chat-Page

### ISSUE THREAD

**Issue by theduusK** [mischkadb/lidarts#133]
I would re-design the chat page.
One big container for the chat and sending a message,
one smaller container for the notification of ended matches
and one container for the "Players online"-list.

At least for me its kind of annoying to see all the "New game" and "Match ended" messages between the normal user chats.

**Comment by mischkadb** [comment]
True. Became an issue in the last days. I will also add a second tab for English speaking players.

**Comment by mischkadb** [comment]
Implemented a few days ago: https://github.com/mischkadb/lidarts/commit/2637ff47a565d603fe53fb7f4489c7cdad70fec9#diff-b8a20508da479d26ed381ba1b24a3b72

No language-separating tabs for now. Lots of private group chatting was moved voluntarily to tournament pages.
