### ISSUE TITLE
Screen numpad on webcam sessions

### ISSUE THREAD

**Issue by loeffelpan** [mischkadb/lidarts#181]
I want to use my iPad to join webcam games.
Unfortunately in webcam games there is no numpad on the screen to fill scores. The screen numpad from non-webcam games would be helpful. Using the on-screen-keyboard of the tablet covers half the screen and I have to hide it after each scoring to see what my opponent does.

Maybe you can add it as second tab beside "Chat" as in other game types.

**Comment by mischkadb** [comment]
You can use the "Show only scoreboard on main device" option in the webcam settings. It forces the non-webcam game page on your tablet. You have to use a phone as a webcam in that case.

Using a tablet for score input, score output, as camera device and to show the opponent's video feed at the same time is intentionally not supported.

**Comment by loeffelpan** [comment]
Thanks. I noticed that option before, but I'm not sure how to use it.
When I activate that option and join a webcam game from tablet and I can just use it for scoring. Fine.
And then I have to join with another device in the same game? Browsing the following site with my phone and call the webcam from tablet seems not to work. Am I doing something wrong?

My setting is as follows:
iPad for score in and out and my phone in follow mode as webcam.
iPad can use desktop mode on lidarts.org and show the site as my laptop does. But as I said there is no numpad. In a non-webcam game on my laptop it's there. Seem to be inconsequent for me.

PS: If you're german we could switch our language to make explainations easier.

**Comment by mischkadb** [comment]
Wir können gerne auf Deutsch schreiben.

Die korrekte Einstellungen für deine Gerätekombination sind "Folge-Modus" und "Scoreboard auf Hauptgerät" aktiviert in den Webcam-Einstellungen. Mit dem Smartphone in der Lobby auf die Folgeseite gehen. Mit dem Tablet im normalen Modus ins Spiel gehen und über den Link im Menü das Smartphone herbeirufen.

Es gibt im Webcamspiel mit Bildanzeige keine Bildschirmtastatur. Es ist bewusst so gebaut, dass Tablets nur als reines Scoreboard ohne Bildanzeige verwendet werden können.

**Comment by loeffelpan** [comment]
OK, verstanden.

Die Sache hat aber einen kleinen Haken. Das iPad beispielsweise lädt die Seite standardmäßig im Desktop-Modus - also so wie aufm dem Laptop mit Kamera-Bild und ohne Bildschirm-Tastatur. Umgehen könnte man das ganze dann noch mit einer Bluetooth-Tastatur am iPad. Aber mit einer Bildschirm-Tastatur (wie im normalen Spiel ja auch IMMER angezeigt wird, unabhängig ob mobiler oder Desktop-Browser) wäre das noch etwas runder.
Und man hätte außerdem das Videobild wenigstens auf ca. 10“ am Tablet und nicht auf 5“ am Smartphone (was ich im Zweifel auch gar nicht sehen kann, da es ja als Kamera dient und ungünstig ausgerichtet ist).

Dann scheine ich noch irgendwas falsch zu machen.
Ich gehe mit dem iPhone in den Follow-Modus. Rufe das Spiel auf dem iPad auf. Und rufe die Kamera herbei. Bei mir passiert dann nichts, wenn “Scoreboard auf Hauptgerät“ aktiv ist. Oder erkenne ich da nur was, wenn noch eine andere Kamera im Spiel ist (also die meines Gegners)? Und das Kamerabild meines Gegners sehe ich dann wirklich nur auf meinem iPhone?

**Comment by mischkadb** [comment]
Mit einer Blutooth-Tastatur spricht aus meiner Sicht auch wenig dagegen, das Tablet als Kameragerät zu verwenden.

Das Videobild gibt es nicht als reine Ausgabe. Sobald Jitsi Meet eingebunden wird funktioniert immer auch das Senden des Bildes. Was du als "Haken" bezeichnest ist absichtlich so designed. Es funktioniert "nur Webcam" (was immer Ein- und Ausgabe bezeichnet, da nicht trennbar), "nur Score" (inkl. Touch) und "Webcam und Score" (ohne Touch). "Webcam und Score" (inkl. Touch) ist nicht vorgesehen.

Dass das Bild auf 10" besser wäre als auf 5" ist mir bewusst, aber wie erwähnt nicht umsetzbar. Deshalb habe ich Tablet + Handykamera als nicht empfohlene, letzte Alternative für Webcamdarts supported. Irgendwo muss die Qualitätsgrenze gezogen werden.

Wenn du die Kamera herbeirufst, dann passiert auf dem Hauptgerät gar nichts optisch. Lediglich das Kameragerät lädt die Seite neu und landet dabei in der korrekten Videokonferenz des Spiels.

**Comment by loeffelpan** [comment]
OK, wenn das absichtlich so gemacht ist, dann bin ich fein damit - das iPad soll im supporteten Fall als nur als Scoreboard dienen.
Als „Haken“ hatte ich auch nur gemeint, dass die Anleitung nicht ganz passt, da das iPad und ggf. andere Tablets gar nicht die mobile Seite laden und somit die Option „Scoreboard auf Hauptgerät“ wirkungslos ist.

Das mit dem „Webcam herbeirufen“ in diesem Modus klappt inzwischen. Ich war einfach schon im Jitsi Meeting drin mit dem Smartphone bevor ich die Cam herbeigerufen habe. So gehts natürlich nicht.

Danke für die Hilfe und die tolle Arbeit auf Lidarts.de.
Weiter so.
