### ISSUE TITLE
Server monitoring and alerts

### ISSUE THREAD

**Issue by mischkadb** [mischkadb/lidarts#27]
I have absolutely no clue how to implement this at the moment and what tools to use. But it will be important if lidarts attracts more players.

**Comment by ernibert** [comment]
You might have a look to the Munin (http://munin-monitoring.org/) project. Its easy to setup and can be configured to create alerts if  thresholds exceeded. Also easy to write own sensors so you can easily monitor application specific metrics, too.

**Comment by mischkadb** [comment]
External monitoring has been implemented for lidarts.org. It's not part of the repo though.
