### ISSUE TITLE
Score ranges in statistics

### ISSUE THREAD

**Issue by mischkadb** [mischkadb/lidarts#95]
Currently 100+ includes 140+, 180 etc. Probably should not happen as it's interpreted differently by most darts statisticians. 

A range 171+ could be added and 140+ changed to 134+. Discussion needed?

**Comment by thomasmiko** [comment]
Ok so we will have the following ranges (in the upper regions):

180
171+
134+
100+
...

Or we can implement it with 180/170+/135+/100+/... ?

In the first example we would have a difference of 34 and 37 points until the next range. So both ranges would have a difference of 35 points.

**Comment by mischkadb** [comment]
I suggest either full 19s or 20/19/18 worst case.

For 19s / 20/19/18:

- 180
- 171+ / 171+
- 133+ / 131+
- 95+ / 93+
- 57+ / 57+

In the end it's an arbitrary decision. 180/171+/131+/91+/57+ looks kinda nice.

**Comment by thomasmiko** [comment]
Ok :) Maybe we can have both (or later more) variants and the user can save a flag in his profile which variant he wan't for his statistics (and the parts where the score will be displayed, like game overview).

1) For 20s
180
140+
100+
80+
60+
40+
20+
<20

2) For 19s
180
171+
133+
95+
76+
57+
38+
19+
<19

**Comment by mischkadb** [comment]
Implemented by https://github.com/mischkadb/lidarts/commit/5448015d46fcef839752a21b8893edaebdcb0184
